---
- name: Deploy Grafana and Prometheus on Kubernetes
  hosts: localhost
  gather_facts: false
  
  tasks:
    - name: Create Namespace
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ k8s_namespace }}"
