---
- name: Deploy Grafana and Prometheus on Kubernetes
  hosts: localhost
  gather_facts: false

  vars:
    k8s_api_server: "https://192.168.1.92:6443"
    k8s_api_token: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN6ekNDQWJlZ0F3SUJBZ0lSQUlaOXJHbnNPVU9jbUlVbHpsSnBOYnN3RFFZSktvWklodmNOQVFFTEJRQXcKRHpFTk1Bc0dBMVVFQXd3RVVFbE9TekFlRncweU5EQXpNREV4T0RVek1qTmFGdzB5T1RBek1ERXhPRFV6TWpOYQpNQTh4RFRBTEJnTlZCQU1NQkZCSlRrc3dnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCCkFRQzJhYlc4Tkhvb0FId3NJM3E5cjE0MHBpRlk4TFp4SHVNQU5hRDhPSmkzNFhiV0ZsTDNEY2RiL3JQM0M0VHMKQndNbG1GZGxpbGZPVUtCaHZtRHpLZlBUWmhQcjVpYmRXSUpSWkV3UGpEZHpuV3p1KzMxZyt1NlZ1Q3NQZ3NtaQpnZFRxWkpUTkRRVTVlcjFvNW1YUGx2S0xYaURvYVRoNnNlcUJDZnNPZFpsSVpiKytLREVHNUI2elg5TUhPc2JhCmZ0YVRLQlc1NzhoRExkMEtxZElCcHowQ1QvSmpxY3lnY0MyWTFuWDQwVEhTR3BWSWlnSmY5eXpYWnR1RXJrMWIKa2cxYklOOTk4OVAyLzByL3BIeFZaekQ1OTJ3QWlrSTJyR2lvalVXQWxHTEdhKzdFZXlsVm1uaFl2amlISzJCRQo3M1RlREtWOUQwb282a3JsKzd6R2N5Z2pBZ01CQUFHakpqQWtNQklHQTFVZEV3RUIvd1FJTUFZQkFmOENBUUF3CkRnWURWUjBQQVFIL0JBUURBZ0lFTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBQTg3ZzFmMVc5UXhqZmZXWDMKTEVKellrRmc5NnhnVWswVC8xYzduNm9tTnBpcVJMeDFPL3M2NEh5UjRSOVRQZkxiNi9rbTVEVERkSjBhVU9XVwphMnhXNWlQczMwWFBMNEgxaU1ZVHRJc213YlMxbFU4Q3UyWEgrWURSVUd4bEEvczJ6ZWdGdjFsaVpMQWVFRkM3Cm16Tm1Nd3h4bWR5b3l6SXpYRWE0ZGRGMERVTDJ4ZkkydEZQVEFhWnh2NlQvTDFseS9RRUUwUDd0QmRweTNhMUYKdnRzQm8xQkRycFYvK3Rsalhpd1E2YjVxWElVL29EVUk3a29PcHgvdW5jVkxHVnI3TDF1UE9SYm9LY0x5SjF6dApHN1JoZ3Ruckw0d3lZcVJkQUJSSHRrcHh6b1NhRlBGVCt0N1lXeUdHOXpEWFMxMzFWTnRIL0dyNmRmZ3ZlTVFNCnlpaWcKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ=="
    k8s_namespace: "monitoring"

  tasks:
    - name: Create Namespace
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ k8s_namespace }}"

    - name: Install Helm
      community.general.helm:
        version: "3"

    - name: Add Helm Repository
      community.general.helm_repository:
        name: prometheus-community
        repo_url: "https://prometheus-community.github.io/helm-charts"

    - name: Install Prometheus
      community.general.helm:
        chart_ref: "prometheus-community/prometheus"
        release_name: "prometheus"
        namespace: "{{ k8s_namespace }}"

    - name: Install Grafana
      community.general.helm:
        chart_ref: "grafana/grafana"
        release_name: "grafana"
        namespace: "{{ k8s_namespace }}"
